services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./Data:/app/Data
      - ./wwwroot/uploads:/app/wwwroot/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
