services:
  web:
    build: .
    ports:
      - "5176:5176"
    volumes:
      - ./wwwroot/uploads:/app/wwwroot/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
